# Generated by Django 4.1.7 on 2024-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(max_length=120)),
                ("password", models.TextField(max_length=50)),
                ("token", models.TextField()),
                ("signInTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UName", models.CharField(max_length=120)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField(max_length=50)),
                ("signUpTime", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Login",
        ),
    ]
